# Generated by Django 4.1.7 on 2023-03-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
