# Generated by Django 4.1.7 on 2023-03-16 03:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('citiesapp', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
